<a href="https://colab.research.google.com/github/JenifferZam/Inteligencia-artificial/blob/main/martes_29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [ ]:
print(type(myArray))

<class 'numpy.ndarray'>


In [ ]:
print(myArray.shape)
print(myArray[2])
myArray[2]=29
print(myArray)

(5,)
3
[ 1  2 29  4  5]


In [ ]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
myArray3=np.zeros((5,5))
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
myArray4=np.full((3,6),10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones((5,5))
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
myArray7=np.random.random((5,5))
print(myArray7)

[[0.98927009 0.12489657 0.46018271 0.54174267 0.71934165]
 [0.95914665 0.2652606  0.50460606 0.33858096 0.52040895]
 [0.28778082 0.88194547 0.1008374  0.14923658 0.55922959]
 [0.94316673 0.16975855 0.67702288 0.26652499 0.46845076]
 [0.41462196 0.58874062 0.58134641 0.49398681 0.27593723]]


In [ ]:
myArray8=np.random.randint(100,size=(5,5))
print(myArray8)

[[ 2 58 44  4 71]
 [16 22 73 24 62]
 [72  4 15 55 84]
 [64 84 99 59 16]
 [62 77 12 64 98]]


In [ ]:
newMatrix=myArray8[:2,:2]
print(newMatrix)

[[ 2 58]
 [16 22]]


In [ ]:
myArray8[2,2]=10000
print(myArray8)

[[    2    58    44     4    71]
 [   16    22    73    24    62]
 [   72     4 10000    55    84]
 [   64    84    99    59    16]
 [   62    77    12    64    98]]


In [ ]:
 print(myArray8[2,:])

[   72     4 10000    55    84]


In [ ]:
print(myArray8[:,2].shape)

(5,)


In [ ]:
subMatrix=myArray8[1:4,1:4]
print(myArray9)

[[   22    73    24]
 [    4 10000    55]
 [   84    99    59]]


In [ ]:
import numpy as np
matrixA=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)

(3, 4)


In [ ]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [ ]:
matrixB = np.random.randint(low=0, high=10, size=(4, 3))
print(matrixB)

[[1 2 1]
 [3 9 1]
 [6 7 6]
 [1 6 0]]


In [ ]:
print(matrixB)
col_indices=np.array([0,1,2])
row_indices=np.array([1,2])

for row,col in zip(row_indices,col_indices):
    #print(row," ",col)
    print(matrixB[row,col])

[[1 2 1]
 [3 9 1]
 [6 7 6]
 [1 6 0]]
3
7


In [ ]:
mast=matrixB>7
print(mast)

[[False False False]
 [False  True False]
 [False False False]
 [False False False]]


In [ ]:
print(matrixB[mast])

[9]


In [ ]:
print(matrixB[matrixB>7])

[9]


In [ ]:
print(matrixB)

[[1 2 1]
 [3 9 1]
 [6 7 6]
 [1 6 0]]


In [ ]:
matrixB[matrixB%2==0]+=100
print(matrixB)

[[  1 102   1]
 [  3   9   1]
 [106   7 106]
 [  1 106 100]]


In [ ]:
print(matrixB)

[[  1 102   1]
 [  3   9   1]
 [106   7 106]
 [  1 106 100]]


In [ ]:
filter=(matrixB>3) & (matrixB<9)
matrixB[filter]+=100
print(matrixB)

[[  1 102   1]
 [  3   9   1]
 [106 107 106]
 [  1 106 100]]


In [ ]:
matrixA1=np.random.randint(0, 10, size=(2,2))
matrixA2=np.random.randint(0, 10, size=(2,2))
print("MatrixA1")
print(matrixA1)
print("MatrixA2")
print(matrixA2)

MatrixA1
[[7 7]
 [8 8]]
MatrixA2
[[0 8]
 [9 4]]


In [ ]:
print(matrixA1+matrixA2)
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)

[[ 7 15]
 [17 12]]
[[ 7 -1]
 [-1  4]]
[[ 0 56]
 [72 32]]
[[       inf 0.875     ]
 [0.88888889 2.        ]]


<ipython-input-27-d9a4810fe26b>:4: RuntimeWarning: divide by zero encountered in divide
  print(matrixA1/matrixA2)


In [ ]:
print(matrixA1)

[[7 7]
 [8 8]]


In [ ]:
print(np.sqrt(matrixA1))

[[2.64575131 2.64575131]
 [2.82842712 2.82842712]]


In [ ]:
matrixA1=np.random.randint(0, 10, size=(2,5))
print(matrixA1)

[[9 9 8 9 2]
 [1 9 1 3 0]]


In [ ]:
print(np.mean(matrixA1))

5.1


In [ ]:
print(matrixA1.mean(axis=1))

[7.4 2.8]


In [ ]:
print(matrixA1.mean(axis=0))

[5.  9.  4.5 6.  1. ]


In [ ]:
print(np.std(matrixA1))

3.78021163428716


In [ ]:
print(np.median(matrixA1))

5.5


In [ ]:
print(matrixA1.sum())

51


In [ ]:
print(np.max(matrixA1))

9


In [ ]:
print(np.min(matrixA1))

0


In [ ]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [ ]:
y=start+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
col_rows=np.array([1,2,3,4])

In [ ]:
print(col_rows.shape)

(4,)


In [ ]:
col_rows=np.array([[1,2,3,4]])
col_rows=col_rows.T
#print(col_rows)
y=start+col_rows
print(y)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
