<a href="https://colab.research.google.com/github/JenifferZam/Inteligencia-artificial/blob/main/Martes_29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [6]:
print(type(myArray))

<class 'numpy.ndarray'>


In [9]:
print(myArray.shape)
print(myArray[2])
myArray[2]=29
print(myArray)

(5,)
3
[ 1  2 29  4  5]


In [10]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
myArray3=np.zeros((5,5))
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
myArray4=np.full((3,6),10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones((5,5))
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
myArray7=np.random.random((5,5))
print(myArray7)

[[0.98927009 0.12489657 0.46018271 0.54174267 0.71934165]
 [0.95914665 0.2652606  0.50460606 0.33858096 0.52040895]
 [0.28778082 0.88194547 0.1008374  0.14923658 0.55922959]
 [0.94316673 0.16975855 0.67702288 0.26652499 0.46845076]
 [0.41462196 0.58874062 0.58134641 0.49398681 0.27593723]]


In [18]:
myArray8=np.random.randint(100,size=(5,5))
print(myArray8)

[[ 2 58 44  4 71]
 [16 22 73 24 62]
 [72  4 15 55 84]
 [64 84 99 59 16]
 [62 77 12 64 98]]


In [19]:
newMatrix=myArray8[:2,:2]
print(newMatrix)

[[ 2 58]
 [16 22]]


In [20]:
myArray8[2,2]=10000
print(myArray8)

[[    2    58    44     4    71]
 [   16    22    73    24    62]
 [   72     4 10000    55    84]
 [   64    84    99    59    16]
 [   62    77    12    64    98]]


In [21]:
 print(myArray8[2,:])

[   72     4 10000    55    84]


In [25]:
print(myArray8[:,2].shape)

(5,)


In [27]:
subMatrix=myArray8[1:4,1:4]
print(myArray9)

[[   22    73    24]
 [    4 10000    55]
 [   84    99    59]]
